Added CDCMMEClinicalConversionFactors codesystem using CQL
cqframework/opioid-cds-r4 pull request #198
Opened 2022-08-04 22:53 UTC by c-schuler

2022-08-04 23:01 UTC, brynrhodes requested changes

2022-08-04 23:01 UTC, brynrhodes commented on input/pagecontent/cql/ConversionFactors.cql
> +  CDCMMEClinicalConversionFactors."CDCMMEClinicalConversionFactorsCodeSystem" C
Yes, exactly, please just add a comment that this is a workaround for the fact that we can't retrieve the CodeSystem resource from the FHIR server.

2022-08-04 23:22 UTC, brynrhodes approved these changes

2022-08-11 17:33 UTC, Capt-Mac approved these changes

2022-08-11 17:33 UTC, merged