335 2016 update quick start guide
cqframework/opioid-cds-r4 pull request #337
Opened 2023-05-25 09:51 UTC by alackerbauer

2016 version of quick start guide

please note that:
* the current response to the hook request does not contain any suggestion element
* the CDS sandbox does return an empty list of cards.

2023-05-30 21:23 UTC, c-schuler requested changes
This does not build using the 1.3.12 version of the publisher.

2023-05-30 21:31 UTC, c-schuler requested changes

2023-05-30 21:31 UTC, c-schuler commented on input/pagecontent/quick-start.xml
> +                "item1": "Patient?_id=Patient/{{context.patientId}}",
Should be using escaped ampersand (&amp;amp;)

2023-05-30 21:31 UTC, c-schuler commented on input/pagecontent/quick-start.xml
> +    <tr><td><a href="requests/QuickStart/opioidcds-10-patient-view-bundle.json">opioidcds-rec10-patientview-bundle</a></td><td>Bundle</td><td>All Required Content for Recommendation #10</td></tr>
Let's refer the user to the _refresh script documentation to generate the bundle. This just adds work for us whenever we update rec10 logic

2023-05-30 21:31 UTC, c-schuler commented on input/pagecontent/quick-start.xml
> +  	  <tr><td><a href="requests/QuickStart/quickstart-medications-bundle.json">quickstart-medications-bundle</a></td><td>Bundle</td><td>Test data for Quick Start test case</td></tr>
Can we point to an existing request or create one for the purposes of the quick start? Similar issue to the change I requested for the artifact bundle

2023-05-30 21:32 UTC, c-schuler requested changes

2023-05-30 21:32 UTC, c-schuler commented on input/pagecontent/quick-start.xml
> +                "item2": "Condition?patient=Patient/{{context.patientId}}&category=http://terminology.hl7.org/CodeSystem/condition-category|encounter-diagnosis",
Should be using escaped ampersand (&amp;amp;)

2023-05-31 08:27 UTC, alackerbauer commented
> This does not build using the 1.3.12 version of the publisher.

fixed by escaping ampersands.

2023-05-31 08:27 UTC, alackerbauer commented on input/pagecontent/quick-start.xml
> +                "item2": "Condition?patient=Patient/{{context.patientId}}&category=http://terminology.hl7.org/CodeSystem/condition-category|encounter-diagnosis",
done. also escaped curly braces since they were interpreted as a non-existing xslt expression

2023-05-31 09:15 UTC, alackerbauer commented on input/pagecontent/quick-start.xml
> +    <tr><td><a href="requests/QuickStart/opioidcds-10-patient-view-bundle.json">opioidcds-rec10-patientview-bundle</a></td><td>Bundle</td><td>All Required Content for Recommendation #10</td></tr>
So should we leave the link to the current requests/Quickstart-bundle for getting started easily and add a note that the latest version of that bundle can only be found when executing _refresh and the location to find it locally would be: bundles/plandefinition/opioidcds-10-patient-view/opioidcds-10-patient-view-bundle.json (?)

or do we aim to put that bundle automatically in our output folder and refer to it from the quick start page?

2023-05-31 09:24 UTC, alackerbauer commented on input/pagecontent/quick-start.xml
> +  	  <tr><td><a href="requests/QuickStart/quickstart-medications-bundle.json">quickstart-medications-bundle</a></td><td>Bundle</td><td>Test data for Quick Start test case</td></tr>
This bundle contains two resources of type MedicationRequest that were a part of this file: [input/pagecontent/requests/OpioidCDSREC10PatientView/request-example-rec-10-patient-view-no-screenings.json](https://github.com/cqframework/opioid-cds-r4/blob/master/input/pagecontent/requests/OpioidCDSREC10PatientView/request-example-rec-10-patient-view-no-screenings.json)

There was nothing existing for those two medications. Would you like us to move this bundle to another folder?

2023-05-31 19:03 UTC, c-schuler commented on input/pagecontent/quick-start.xml
> +                "item2": "Condition?patient=Patient/{{context.patientId}}&category=http://terminology.hl7.org/CodeSystem/condition-category|encounter-diagnosis",
We actually need the double brackets (see the [cds hooks docs](https://cds-hooks.hl7.org/2.0/#prefetch-template) on prefetch template for more info). Use this: `{{'{{'}}context.patientId}}`

2023-05-31 19:05 UTC, c-schuler commented on input/pagecontent/quick-start.xml
> +  	  <tr><td><a href="requests/QuickStart/quickstart-medications-bundle.json">quickstart-medications-bundle</a></td><td>Bundle</td><td>Test data for Quick Start test case</td></tr>
Feel free to add those resources as examples (input/examples) and reference them directly (preferably as stand-alone resources - a bundle isn't really needed here)

2023-05-31 19:13 UTC, c-schuler commented on input/pagecontent/quick-start.xml
> +    <tr><td><a href="requests/QuickStart/opioidcds-10-patient-view-bundle.json">opioidcds-rec10-patientview-bundle</a></td><td>Bundle</td><td>All Required Content for Recommendation #10</td></tr>
Hmm. You raise a good point: is it reasonable to require the user to run the _refresh script within a quick-start guide? I could see that being a significant hurdle for non-technical users. Although, this guide requires them to have a local instance of the cqf-ruler stood up. Due to that requirement, I don't think it is unreasonable to have the user generate the bundle. Does that make sense?

2023-06-13 22:26 UTC, c-schuler approved these changes
Looks good! Please make note of the changes in my last commit and include them in the 2022 PR (#336)

2023-06-13 22:26 UTC, merged